Framework
AleksandrVoyteshenko/Framework pull request #1
Opened 2020-12-21 14:47 UTC by AleksandrVoyteshenko

2020-12-24 12:50 UTC, nitrogen16 requested changes

2020-12-28 06:20 UTC, AleksandrVoyteshenko commented on src/test/java/model/VirtualMachine.java
> +package model;
fixed

2020-12-28 06:25 UTC, AleksandrVoyteshenko commented on src/test/java/service/CreatorVM.java
> +    public static VirtualMachine withCredentialsFromProperty() {
getVirtualMachineWithDataFromProperties

2020-12-28 06:27 UTC, AleksandrVoyteshenko commented on src/test/java/test/HardCoreTest.java
> +                .addMailAddress(mail, nameValueField);
adds an email address in the required field and sends a letter

2020-12-28 06:27 UTC, AleksandrVoyteshenko commented on src/test/java/driver/DriverSingleton.java
> +public class DriverSingleton {
Fixed

2020-12-28 07:00 UTC, AleksandrVoyteshenko commented on src/test/resources/aqa.properties
> +testdata.desiredResultLocalSSD = 2x375
test data

2020-12-28 07:00 UTC, AleksandrVoyteshenko commented on src/test/resources/dev.properties
> +testdata.desiredResultLocalSSD = 1x375
test data

2021-01-24 14:16 UTC, AleksandrVoyteshenko commented
Merge branch framework

2021-01-24 14:17 UTC, merged